apiVersion: v1
kind: Service
metadata:
  name: {{svc_name}}
  namespace: {{namespace}}
spec:
  ports:
  - port: {{svc_port}}
    protocol: TCP
    targetPort: {{port_name}}
  selector:
    app: {{app_name}}
  type: ClusterIP